### ISSUE TITLE
Generator doesn't play with "bundle add phlex-rails" (gem "phlex-rails", "~> 1.1")

### ISSUE THREAD

**Issue by MyklClason** [rubymonolith/superform#16]
I ran the generator for this, and it added another `phlex-rails` at the bottom, which then caused bundler to error.

I ended up having to comment out `gem "phlex-rails", "~> 1.1"`, then the generator, then delete the `gem "phlex-rails"` then run `bundle update phlex-rails` (just to be sure). So not really a major issue, but would be nice if it wasn't needed.

**Comment by bradgessler** [comment]
I want into this a few days ago too. The generator needs to detect if `phlox-rails` is already installed and skip that step if it is.

**Comment by bradgessler** [comment]
Fixed by commit https://github.com/rubymonolith/superform/commit/35697ed99b428c49fd0d3da37377d46a7495ce2d

**Comment by bradgessler** [comment]
Released in 0.4.6
