### ISSUE TITLE
noob question

### ISSUE THREAD

**Issue by Z2Flow** [rubymonolith/superform#17]
I can render a form from an ERB template, but cannot from a Phlex ApplicationView.
Using the example, when I render the form, the error message is:
  `"undefined method `persisted?' for nil"` at
  ` app/views/forms/application_form.rb:12:in `around_template' `

Is this my lack of knowledge or an issue?

**Comment by bradgessler** [comment]
I can't tell from the context you provided. If you're still trying to figure this out could you start a discussion at https://github.com/rubymonolith/superform/discussions?

**Comment by Z2Flow** [comment]
Brad,

Thanks for getting back to me.
Can you resend the discussion link please, as it produces a 404.

Cheers,
Rob
