### ISSUE TITLE
Support form `enctype` attribute for file inputs

### ISSUE THREAD

**Issue by henri42** [rubymonolith/superform#3]
Hello,

I am in the process of starting a Rails project using Phlex and Superform. In my project, I need to upload files to the server. However, I've noticed that Superform currently does not provide a straightforward way to set the `enctype` attribute to `multipart/form-data`.

The form tag in Superform is currently only supporting `form_action` and `form_method` as follows:
```ruby
      def around_template(&)
        form action: form_action, method: form_method do
          authenticity_token_field
          _method_field
          super
        end
      end
```

Would it be possible to initialize a Superform object with `@enctype` as for `@action` and `@method` ? And why not `novalidate` and `target` to have a full HTML form covering.

If the above is not possible, should I consider overloading the `around_template` method in the `application_form.rb` side?

Thanks a lot, very nice gem !

**Comment by bradgessler** [comment]
0.4.2 adds support for passing attributes to the form tag, including the `enctype` attribute.

**Comment by henri42** [comment]
Sorry for not being active on this topic, thanks a lot for the work it will be very useful !
