### ISSUE TITLE
File with ActiveStorage cause ActiveSupport::MessageVerifier::InvalidSignature without enctype

### ISSUE THREAD

**Issue by nolantait** [rubymonolith/superform#32]
Full error is:

```
ActiveSupport::MessageVerifier::InvalidSignature: mismatched digest
```

This can be fixed by adding the `enctype` attribute to `multipart/form-data`:

```ruby
render Some::Form.new(@model, enctype: "multipart/form-data")
```

Maybe for now putting a note into the README? Can't think of an obvious way of passing this back up to the `around_template` call. Maybe introspecting the form in that method?

**Comment by ediathome** [comment]
I had the same issue last week and would also vote for mentioning it in the README

**Comment by bradgessler** [comment]
Does it make sense for this value to be the default? In theory it works for forms with or without files. What’s the downside to this being enabled by default?

If there is an issue enabling this by default, it might be possible to detect when a file field is used to automatically set the form to this encoding type.

Regardless, I agree this should be in the docs.

**Comment by nolantait** [comment]
GET based form semantics would be ruined and it would bloat the size of your requests slightly from what I can gather online.

I was thinking of flagging the field when the methods are called but it would require people implementing their own fields to call super or flat themselves. Same problem if we just add introspection for the types as it depends on controlling the input calls.

**Comment by bradgessler** [comment]
Ah that would be bad if the GET semantics were ruined.

Seems like docs is the way to go.

**Comment by ediathome** [comment]
Just [opened a PR](https://github.com/rubymonolith/superform/pull/34) with a potential addition to the docs
