### ISSUE TITLE
`def template` will be deprecated in Phlex 2.0

### ISSUE THREAD

**Issue by joostvanrijn** [rubymonolith/superform#35]
I just upgraded to Phlex 1.10 and my specs and features are spewing this deprecation message:

> ⚠️ [DEPRECATION] Defining the `template` method on a Phlex component will not be supported in Phlex 2.0. Please rename the method to `view_template` instead.

I will create a pull request that resolves this. (Please bear with me. It will be my first.)

**Comment by wdiechmann** [comment]
@bradgessler is there anything holding this PR (or rather the 'fix' of `def template` => `def view_template`) back?

asking 'cause my OCD keeps my eyes bleeding 🤣

**Comment by bradgessler** [comment]
Waiting for Phlex 2.x to leave beta, then I'll cut everything over to `view_template`.

**Comment by bradgessler** [comment]
This change was shipped in https://github.com/rubymonolith/superform/commit/7795d1c7d1d760445f291e7f4d2398bbda8e5500
