### ISSUE TITLE
render field with a block leads to ArgumentError

### ISSUE THREAD

**Issue by goldelehr** [rubymonolith/superform#39]
Hello,

when running the example code from the README's Form Field Guide i get an ArgumentError upon reaching this block:

```
render field(:reason) do |f|
  div do
    f.label { "Why should we care about you?" }
    f.textarea(row: 3, col: 80)
  end
end
```

i get this error: 
`ArgumentError #<Superform::Rails::Form::Field:0x00007f849562e168 @key=:reason, .... > (is not an ActiveModel-compatible object. It must implement :to_partial_path.)`

I'm renderung the form with 
`render SignupForm.new @user`

with `@user` being an ActiveRecord backed entity.

Is there something wrong with how i call the form?

Thanks for your help

**Comment by ediathome** [comment]
Hi goldelehr,
does your ActiveRecord model for your @user object have a field reason:
Probably not and my guess is that this is causing the error…
So add a :reason datafield to your AR model and it should work.

**Comment by goldelehr** [comment]
Hi ediathome,

Yes, my application has a user object that contains a 'reason' field. The issue arises when `ActionView::AbstractRenderer::ObjectRendering` attempts to access the `to_partial_path` method on an `ApplicationForm::Field` object, which does not exist for these specific objects. However, it does exist for the underlying user object.

**Comment by bradgessler** [comment]
I think the items in the block still need to be rendered. Try this:

```ruby
field(:reason) do |f|
  div do
    render f.label { "Why should we care about you?" }
    render f.textarea(row: 3, col: 80)
  end
end
```

If that works, I'd accept a PR that fixes the docs.

**Comment by goldelehr** [comment]
Works perfectly, thanks! I created PR #44
