### ISSUE TITLE
private method `select' called for #<Superform::Rails::Form::Field

### ISSUE THREAD

**Issue by HalfBloody** [rubymonolith/superform#6]
Hi, Superform looks very promising. So I wanted to play around with it. Unfortunately I run into an error immediately when trying to create a select field:

```
    row field(:payment_direction).select Document.payment_directions.keys
```

Where document payment_directions is:

```
  enum payment_direction: {
    debit: 0,
    credit: 1,
  }
```

in
```    
class Front::Documents::Form < ApplicationForm
  def template(&)
    row field(:kind).input
    row field(:payment_direction).select Document.payment_directions.keys
    row field(:identifier).input
    row field(:vat_amount).input
    row field(:total_amount).input
    row field(:google_drive_identifier).input
    row field(:currency_code).select Currency.pluck(:code)
    row field(:issue_date).input
    row field(:due_date).input
    row field(:counterparty_id).select Currency.pluck(:code)
  end
end
```

And render it with:

```
= render Front::Documents::Form.new @document
```

I'm using:
Rails: 7.0.8
Ruby: 3.2.2
Superform: 0.4.0

Here is the full error:

```ActionView::Template::Error (private method `select' called for #<Superform::Rails::Form::Field:0x0000000148331500 @key=:payment_direction, @parent=#<Superform::Namespace:0x0000000148331dc0 @key="document", @parent=nil, @object=#<Document id: 212, user_id: 1, counterparty_id: nil, outgoing: nil, identifier: "POCKET202308-24", amount: 0.5e4, vat_amount: 0.0, total_amount: 0.5e4, issue_date: "2023-08-24", due_date: nil, description: nil, created_at: "2023-10-31 18:33:35.222676000 +0000", updated_at: "2023-11-02 08:47:54.045809000 +0000", kind: "invoice", state: "ready_for_export", digest: "129bcbc0fd164ac7463b1e7085476505b5936c7fdf2262f9e9...", account_id: 1, currency_code: "USD", original_id: nil, payment_direction: "credit", slug: nil, google_drive_identifier: "", kind_certainty: nil, payment_direction_certainty: nil, document_payments_count: 1, text: nil, created: nil, delivery_date: nil>, @field_class=Superform::Rails::Form::Field, @children={:kind=>#<Superform::Rails::Form::Field:0x0000000148331b40 @key=:kind, @parent=#<Superform::Namespace:0x0000000148331dc0 ...>, @object=#<Document id: 212, user_id: 1, counterparty_id: nil, outgoing: nil, identifier: "POCKET202308-24", amount: 0.5e4, vat_amount: 0.0, total_amount: 0.5e4, issue_date: "2023-08-24", due_date: nil, description: nil, created_at: "2023-10-31 18:33:35.222676000 +0000", updated_at: "2023-11-02 08:47:54.045809000 +0000", kind: "invoice", state: "ready_for_export", digest: "129bcbc0fd164ac7463b1e7085476505b5936c7fdf2262f9e9...", account_id: 1, currency_code: "USD", original_id: nil, payment_direction: "credit", slug: nil, google_drive_identifier: "", kind_certainty: nil, payment_direction_certainty: nil, document_payments_count: 1, text: nil, created: nil, delivery_date: nil>, @value=nil, @dom=<id="document_kind" name="document[kind]" value="invoice"/>>, :payment_direction=>#<Superform::Rails::Form::Field:0x0000000148331500 ...>}>, @object=#<Document id: 212, user_id: 1, counterparty_id: nil, outgoing: nil, identifier: "POCKET202308-24", amount: 0.5e4, vat_amount: 0.0, total_amount: 0.5e4, issue_date: "2023-08-24", due_date: nil, description: nil, created_at: "2023-10-31 18:33:35.222676000 +0000", updated_at: "2023-11-02 08:47:54.045809000 +0000", kind: "invoice", state: "ready_for_export", digest: "129bcbc0fd164ac7463b1e7085476505b5936c7fdf2262f9e9...", account_id: 1, currency_code: "USD", original_id: nil, payment_direction: "credit", slug: nil, google_drive_identifier: "", kind_certainty: nil, payment_direction_certainty: nil, document_payments_count: 1, text: nil, created: nil, delivery_date: nil>, @value=nil, @dom=<id="document_payment_direction" name="document[payment_direction]" value="credit"/>>):```

**Comment by bradgessler** [comment]
Oops, looks like I didn't release the `select` method for fields (I just left it in main). I just cut a new gem so run `bundle update superform` and try that again.

I'll close the issue, but open it if you get this error after running 0.4.1.
